<?php

// SPOTIFY API APPLICATION CREDENTIALS
$client_id = "3e02d929c0e543ad85bb421c103059b3";
$client_secret = "";

// THE APPLICATION USER AND SELECTED PLAYIST ID
$open_playlist_userid = "MY-SPOTIFY-USERID";
$open_playlist_id = "MY-SPOTIFY-USER-PLAYLIST";

// READ THE DOCUMENTATION TO OBTAIN REFRESH TOKEN
$refresh_token = "";

